### ISSUE TITLE
The text-search box doesn't work

### ISSUE THREAD

**Issue by jpivarski** [research-software-collaborations/project_database#36]
I don't know what it's doing, but it's not selecting projects by title or abstract text matches.

For instance, there's one project with "Julia" in the title and another that has "Julia" in its abstract:

  * Julia for the Analysis Grand Challenge: Implement an analysis pipeline for the Analysis Grand Challenge (AGC) using JuliaHEP ecosystem.
  * Bayesian Analysis with pyhf: Build a library on top of the pyhf Python API to allow for Bayesian analysis of HistFactory models.

But this is what the text-search on http://research-software-collaborations.org/projects narrows it to:

![image](https://github.com/research-software-collaborations/project_database/assets/1852447/a8889ae5-c0d1-4fcc-9cf5-437aaee92f2e)

Neither of these projects mention "Julia" (not even as mentor names).

**Comment by davidlange6** [comment]
Hum. Thanks for the bug report. This did used to work.. but indeed, I see the same as you now. Will investigate tomorrow

From: Jim Pivarski ***@***.***>
Date: Monday, May 15, 2023 at 7:34 PM
To: research-software-collaborations/project_database ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [research-software-collaborations/project_database] The text-search box doesn't work (Issue #36)

I don't know what it's doing, but it's not selecting projects by title or abstract text matches.

For instance, there's one project with "Julia" in the title and another that has "Julia" in its abstract:

  *   Julia for the Analysis Grand Challenge: Implement an analysis pipeline for the Analysis Grand Challenge (AGC) using JuliaHEP ecosystem.
  *   Bayesian Analysis with pyhf: Build a library on top of the pyhf Python API to allow for Bayesian analysis of HistFactory models.

But this is what the text-search on http://research-software-collaborations.org/projects narrows it to:

[image]<https://user-images.githubusercontent.com/1852447/238501421-a8889ae5-c0d1-4fcc-9cf5-437aaee92f2e.png>

Neither of these projects mention "Julia" (not even as mentor names).

**Comment by davidlange6** [comment]
Fixed now... My attempt to sort projects broke this.
