### ISSUE TITLE
Turn on pre-commit.ci

### ISSUE THREAD

**Issue by matthewfeickert** [research-software-collaborations/project_database#6]
There are pre-commit hooks but they aren't being checked for the project which means that trying to run them creates noisy diffs. Please add https://pre-commit.ci/ so that pre-commit runs in CI on PRs.

**Comment by davidlange6** [comment]
ok - I have yaml checking in two places with different settings.. indeed, the precommit.ci stuff is not enabled yet (was copied over from some repo) - will straighten that out.

**Comment by matthewfeickert** [comment]
@davidlange6 can we please turn on pre-commit.ci? It is pointless to have pre-commit if it isn't going to be used and have it broken like it is now.
