### ISSUE TITLE
By default don't show Complete or Closed projects

### ISSUE THREAD

**Issue by matthewfeickert** [research-software-collaborations/project_database#82]
While https://research-software-collaborations.org/projects allows you the ability to filter on status

https://github.com/research-software-collaborations/project_database/blob/c74e8ede1b1b5ff19063f218886cf35d1b365cf4/project_metadata.yml#L46-L50

I have the feeling that a lot of people are just going to start reading the page and not realize that they need to filter before looking for projects. Is it possible to by deafult exclude `Complete` and `Obsolete/Closed` projects?

cc @davidlange6

**Comment by davidlange6** [comment]
I believe that the iris-hep projects page - 

http://research-software-collaborations.org/projects_irishep

does this already.

**Comment by matthewfeickert** [comment]
Ah okay, indeed. The page is currently not linked from the IRIS-HEP Fellows page, we're just at

> Applications for the Graduate Fellows program are not yet open, but will appear again in 2024.

> so that might be why I didn't notice it.

Is https://research-software-collaborations.org/projects actively used by other communities beyond IRIS-HEP? If yes, seems like this would still be useful to impliment.

**Comment by davidlange6** [comment]
now also updated.
